buildscript {
    repositories {
        gradlePluginPortal()
        jcenter()
        maven {
            url "https://maven.google.com"
        }
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:8.10.0'
        classpath 'org.xtext.xtend:org.xtext.xtend.gradle.plugin:4.0.0'
    }
}

apply plugin: 'com.android.application'
apply plugin: 'org.xtext.xtend'

xtend {
    applyJavaPlugin = false
}

repositories {
    jcenter()
    maven {
        url "https://maven.google.com"
    }
}

android {
    compileSdkVersion 29
    buildToolsVersion '29.0.3'

    defaultConfig {
        minSdkVersion 14
        targetSdkVersion 29
        versionCode 41
        versionName "v4.3"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }

    dependencies {
        implementation 'androidx.appcompat:appcompat:1.7.0'
        implementation 'androidx.legacy:legacy-support-v4:1.0.0'
        implementation 'org.eclipse.xtend:org.eclipse.xtend.lib:2.38.0'
        implementation 'com.github.tobykurien:xtendroid:0.13'
        implementation 'com.github.bumptech.glide:glide:4.16.0'

        testImplementation 'junit:junit:4.13'
        androidTestImplementation 'com.android.support:support-annotations:28.0.0'
        androidTestImplementation 'com.android.support.test:runner:1.0.2'
    }

    buildTypes {
        debug {
            applicationIdSuffix '.debug'
            versionNameSuffix '-DEBUG'
        }
    }

    packagingOptions {
        exclude 'META-INF/eclipse.inf'
        exclude 'META-INF/ECLIPSE_.SF'
        exclude 'META-INF/ECLIPSE_.RSA'
    }

    lintOptions {
        abortOnError false // because missing translations...
    }

    namespace 'com.tobykurien.webapps'
}

task runApp(type: Exec) {
    commandLine '/usr/local/bin/adb', 'shell', 'monkey -p com.tobykurien.webapps.debug -c android.intent.category.LAUNCHER 1'
}
